pipeline:
  build:
    image: plugins/git
    commands:
      - "sh build.sh"
  github_release:
    image: plugins/github-release
    files:
      - "*.tar.gz"
    secrets: [github_token]
    when:
      event: [tag]
  pushbear:
    image: thesues/drone-pushbear
    url: XXXX
    secrets: [sendkey]
    when: 
      success: false
      failure: false
      change: true

